### ISSUE TITLE
Alternate to unsafeWindow ?

### ISSUE THREAD

**Issue by LuckyPed** [Mr-VIT/SteamWebTools#18]
Hello,
I want to use your Script in Chromium,
Using CefSharp.
The Dev-Tools in there give me error of unsafeWindow is undefined.

i checked and turn out Chromium Doesn't support it.

is there any other way i can give value to W instead of W = unsafeWindow ?

your really old version did not use unsafeWindow , now i come to get your new version but it no longer work because of this unsafeWindow,

I hope u can help me, and Thanks anyway for your really usefull script :) 
I'm really an old user, since before it get English language, even donated once back then :+1:

**Comment by Mr-VIT** [comment]
unsafeWindow  = window

**Comment by LuckyPed** [comment]
Well ... Tnx lol
btw new Edition u gave for TM and GM separately , both work for me now in my Chromium w'o any edit !

there was another problem which was : 
for example i got 10 page of items,
i click hide duplicate and it turn into 3 page !
then i click a batch of 50x game for example ... and it turn back to 10 page and everything is messy :|

i checked GM version first then TM version , 
then i wanted to take Screenshot and post here but it got fixed by itself ! now it's working perfectly O.o

Thanks anyway :)

**Comment by Mr-VIT** [comment]
difference between GM and TM versions - TM has meta:
```
// @grant		GM_xmlhttpRequest
// @grant		GM_xhr
// @grant		GM_getValue
// @grant		GM_setValue
// @grant		GM_deleteValue
```
